<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder {

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run() {


        Schema::disableForeignKeyConstraints();
        \DB::table('users')->truncate();
        Schema::enableForeignKeyConstraints();

        \DB::table('users')->insert(array(
            0 =>
            array(
                'id' => 1,
                'name' => 'Vivek',
                'email' => 'vivekmohan@zco.com',
                'speciality_id' => 1,
                'hospital_name' => 'ZCO',
                'npi_number' => '1234567890',
                'city' => 'Kochi',
                'contact_number' => '1234567890',
                'profile_description' => NULL,
                'gender' => 'M',
                'dob' => '1990-01-01',
                'profile_image' => NULL,
                'password' => '$2y$10$HAdElHxmzgByU1xP2qnpX.wZPRk6GcHx4bwTGIvDBio57A9FxFrc6',
                'user_role' => 'D',
                'activation_code' => NULL,
                'code_expires_at' => NULL,
                'is_subscribed' => 'N',
                'is_account_active' => 'Y',
                'left_menu_display_type' => '0',
                'remember_token' => 'F2YRMa21VxQPWmAmgr1lUnLfwffNmBMtKsxmJR9rBrzzdsxVvnVoPtZl2gyJ',
                'parent_id' => NULL,
                'last_logged_in' => '0000-00-00 00:00:00',
                'created_at' => NULL,
                'updated_at' => '2017-03-20 06:47:31',
                'stripe_active' => 0,
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'trial_ends_at' => NULL,
                'subscription_ends_at' => NULL,
                'default_card' => NULL,
                'doximity_id' => NULL,
            ),
            1 =>
            array(
                'id' => 2,
                'name' => 'Binishma',
                'email' => 'test@test.com',
                'speciality_id' => 1,
                'hospital_name' => 'ZCO',
                'npi_number' => '1234567890',
                'city' => 'Kochi',
                'contact_number' => '1234567890',
                'profile_description' => NULL,
                'gender' => 'F',
                'dob' => '1990-01-01',
                'profile_image' => '2_1489394590_profile.jpg',
                'password' => '$2y$10$WM9fSIr5.3VBuTB1xwy2LuNDSU7QVsC6oKbG8.wEZ/KVqdg3RSFki',
                'user_role' => 'D',
                'activation_code' => NULL,
                'code_expires_at' => NULL,
                'is_subscribed' => 'N',
                'is_account_active' => 'Y',
                'left_menu_display_type' => '0',
                'remember_token' => 'c6zL7lIqCZZEmOV7UoCXIqgg0E4IvcXUjPCgdbjLK1lvSJ54QHIuUEjD7ArS',
                'parent_id' => NULL,
                'last_logged_in' => '0000-00-00 00:00:00',
                'created_at' => NULL,
                'updated_at' => '2017-03-21 09:10:42',
                'stripe_active' => 0,
                'stripe_id' => 'cus_AI6PFH3CxE3mTQ',
                'card_brand' => 'MasterCard',
                'card_last_four' => '4444',
                'trial_ends_at' => NULL,
                'subscription_ends_at' => '2017-04-15 07:10:54',
                'default_card' => 'card_19xWGLGKvcXNgPTQr4K5RLK9',
                'doximity_id' => NULL,
            ),
            2 =>
            array(
                'id' => 3,
                'name' => 'Prajina',
                'email' => 'prajina@gmail.com',
                'speciality_id' => 1,
                'hospital_name' => 'ZCO',
                'npi_number' => '1234567890',
                'city' => 'Kochi',
                'contact_number' => '1234567890',
                'profile_description' => NULL,
                'gender' => 'F',
                'dob' => '1990-01-01',
                'profile_image' => '3_1486626241_profile.jpg',
                'password' => '$2y$10$0puNAAG78.MDUnsf2pc5wu5fkmKG4l8aYDE1hYxobOiqH/OYfkdv6',
                'user_role' => 'D',
                'activation_code' => NULL,
                'code_expires_at' => NULL,
                'is_subscribed' => 'N',
                'is_account_active' => 'Y',
                'left_menu_display_type' => '0',
                'remember_token' => 'SqoHBLZNchoCn4dAuOSYA3RzJrFMP43ovm6ceZyzZhu46wDUozM7gHxXOgQQ',
                'parent_id' => NULL,
                'last_logged_in' => '0000-00-00 00:00:00',
                'created_at' => NULL,
                'updated_at' => '2017-03-15 07:05:36',
                'stripe_active' => 0,
                'stripe_id' => 'cus_AFxAqxPOC37dUq',
                'card_brand' => 'MasterCard',
                'card_last_four' => '5100',
                'trial_ends_at' => NULL,
                'subscription_ends_at' => '2017-04-09 18:58:35',
                'default_card' => NULL,
                'doximity_id' => NULL,
            ),
            3 =>
            array(
                'id' => 4,
                'name' => 'adminstaff1',
                'email' => 'adminstaff167676@gmail.com',
                'speciality_id' => NULL,
                'hospital_name' => NULL,
                'npi_number' => NULL,
                'city' => NULL,
                'contact_number' => NULL,
                'profile_description' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'profile_image' => NULL,
                'password' => '$2y$10$paDe7AB3zug.gG8gJ8kkW.y2G88wAUT7QQwEVAFuLFRZw1AL94HzO',
                'user_role' => 'S',
                'activation_code' => NULL,
                'code_expires_at' => NULL,
                'is_subscribed' => 'N',
                'is_account_active' => 'Y',
                'left_menu_display_type' => '0',
                'remember_token' => NULL,
                'parent_id' => 3,
                'last_logged_in' => '0000-00-00 00:00:00',
                'created_at' => '2017-02-14 20:07:56',
                'updated_at' => '2017-02-21 01:18:04',
                'stripe_active' => 0,
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'trial_ends_at' => NULL,
                'subscription_ends_at' => '0000-00-00 00:00:00',
                'default_card' => NULL,
                'doximity_id' => NULL,
            ),
            4 =>
            array(
                'id' => 5,
                'name' => 'Test',
                'email' => 'test@gmail.com',
                'speciality_id' => NULL,
                'hospital_name' => NULL,
                'npi_number' => NULL,
                'city' => NULL,
                'contact_number' => NULL,
                'profile_description' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'profile_image' => NULL,
                'password' => '$2y$10$plmzt94xxt6FAtFwqqEcP.gQHbMk/DtFHES41KnopvwQQG2cV0Ve6',
                'user_role' => 'S',
                'activation_code' => NULL,
                'code_expires_at' => NULL,
                'is_subscribed' => 'N',
                'is_account_active' => 'Y',
                'left_menu_display_type' => '0',
                'remember_token' => NULL,
                'parent_id' => 3,
                'last_logged_in' => '0000-00-00 00:00:00',
                'created_at' => '2017-02-17 01:00:15',
                'updated_at' => '2017-02-17 01:00:15',
                'stripe_active' => 0,
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'trial_ends_at' => NULL,
                'subscription_ends_at' => '0000-00-00 00:00:00',
                'default_card' => NULL,
                'doximity_id' => NULL,
            ),
            5 =>
            array(
                'id' => 6,
                'name' => 'test',
                'email' => 'test123@gdfgdf.com',
                'speciality_id' => NULL,
                'hospital_name' => NULL,
                'npi_number' => NULL,
                'city' => NULL,
                'contact_number' => NULL,
                'profile_description' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'profile_image' => NULL,
                'password' => '$2y$10$4WBOdf0Q/agethc4kHGB4.5JhogbZMscTWPRXEUbEQp98MisNtSU2',
                'user_role' => 'S',
                'activation_code' => NULL,
                'code_expires_at' => NULL,
                'is_subscribed' => 'N',
                'is_account_active' => 'Y',
                'left_menu_display_type' => '0',
                'remember_token' => NULL,
                'parent_id' => 1,
                'last_logged_in' => '0000-00-00 00:00:00',
                'created_at' => '2017-02-20 22:07:04',
                'updated_at' => '2017-02-20 22:07:04',
                'stripe_active' => 0,
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'trial_ends_at' => NULL,
                'subscription_ends_at' => '0000-00-00 00:00:00',
                'default_card' => NULL,
                'doximity_id' => NULL,
            ),
            6 =>
            array(
                'id' => 7,
                'name' => 'test',
                'email' => 'test343@sdfsf.com',
                'speciality_id' => NULL,
                'hospital_name' => NULL,
                'npi_number' => NULL,
                'city' => NULL,
                'contact_number' => NULL,
                'profile_description' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'profile_image' => NULL,
                'password' => '$2y$10$aoEfKWZSwquSd6rLlUVI1O/FwMLzpWfO2QtzlY61/ylBY0KpWx8aq',
                'user_role' => 'S',
                'activation_code' => NULL,
                'code_expires_at' => NULL,
                'is_subscribed' => 'N',
                'is_account_active' => 'Y',
                'left_menu_display_type' => '0',
                'remember_token' => NULL,
                'parent_id' => 3,
                'last_logged_in' => '0000-00-00 00:00:00',
                'created_at' => '2017-02-21 01:17:31',
                'updated_at' => '2017-02-21 01:17:31',
                'stripe_active' => 0,
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'trial_ends_at' => NULL,
                'subscription_ends_at' => '0000-00-00 00:00:00',
                'default_card' => NULL,
                'doximity_id' => NULL,
            ),
            7 =>
            array(
                'id' => 11,
                'name' => 'Pra Jina',
                'email' => 'prajinapk@hq.microobjects.net',
                'speciality_id' => NULL,
                'hospital_name' => NULL,
                'npi_number' => NULL,
                'city' => 'Snohomish',
                'contact_number' => NULL,
                'profile_description' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'profile_image' => NULL,
                'password' => '',
                'user_role' => 'D',
                'activation_code' => NULL,
                'code_expires_at' => NULL,
                'is_subscribed' => 'N',
                'is_account_active' => 'Y',
                'left_menu_display_type' => '0',
                'remember_token' => 'aNrc9OJICKrkxnwMgiTQkvyRXVVaWxMYVwkkZLZr5DTKLou0E6WsV7Iq72iU',
                'parent_id' => NULL,
                'last_logged_in' => '0000-00-00 00:00:00',
                'created_at' => '2017-03-21 12:23:20',
                'updated_at' => '2017-03-22 04:07:12',
                'stripe_active' => 0,
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'trial_ends_at' => NULL,
                'subscription_ends_at' => NULL,
                'default_card' => NULL,
                'doximity_id' => '7410658',
            ),
        ));
    }

}
