<!-- Modal for User Accepts the Terms & Conditions Starts here -->
<div class="modal fade" id="myModalTermsAgreement">
  <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered">
  
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <!-- <button type="button" class="close" id="redirectCancel" data-dismiss="modal">&times;</button> -->
        <h1 class="modal-title">SaaS End User License Agreement</h1>
      </div>
      <div class="modal-body" style="max-height:550px;overflow-y:scroll;">
        <input type="hidden" id="redirect-csrf-roken" value="<?php echo e(csrf_token()); ?>">
        <input type="hidden" id="userRoleAgreement">
        <input type="hidden" id="userIdAgree">
        <?php 
          $userRole = Auth::user()->user_role;
          if ($userRole==='D' || $userRole==='S')
            $redirect = '/physician/subscription';
          else 
            $redirect = '/patient/subscription';
        ?>      
        <!--Content Area-->
        <p>This Software as a Service (SaaS) End User License Agreement (”<b>Agreement</b>”) is a binding agreement between you (”<b>End User</b>” or “<b>you</b>”) and LinkBox Solutions (”<b>Company</b>”). This Agreement governs your use of the software on the web-enabled platform (including all related documentation, the “<b>Application</b>”). The Application is licensed, not sold, to you.</p>
            <p><b>BY CLICKING THE “AGREE” BUTTON AND/OR OTHERWISE USING THE APPLICATION, YOU (A) ACKNOWLEDGE THAT YOU HAVE READ AND UNDERSTAND THIS AGREEMENT; (B) REPRESENT THAT YOU ARE 18 YEARS OF AGE OR OLDER/OF LEGAL AGE TO ENTER INTO A BINDING AGREEMENT; AND (C) ACCEPT THIS AGREEMENT AND AGREE THAT YOU ARE LEGALLY BOUND BY ITS TERMS. IF YOU DO NOT AGREE TO THESE TERMS, DO NOT USE THE APPLICATION.</b></p>
            <p>1.  <u>License Grant</u>. Subject to the terms of this Agreement, Company grants you a limited, non-exclusive, royalty-free and nontransferable license to access, stream, and use the Content and Services (as defined in Section 5) made available in or otherwise accessible through the Application for internal business purposes, strictly in accordance with this Agreement and the Terms of Use applicable to such Content and Services as set forth in Section 5.</p>
            <p>2.  <u>License Restrictions</u>. Licensee will not:</p>
            <ul style="line-height: 28px;">
                <li>a). copy the Application, except as expressly permitted by this license;</li>
                <li>b). modify, translate, adapt, or otherwise create derivative works or improvements, whether or not patentable, of the Application;</li>
                <li>c). reverse engineer, disassemble, decompile, decode, or otherwise attempt to derive or gain access to the source code of the Application or any part thereof;</li>
                <li>d). remove, delete, alter, or obscure any trademarks or any copyright, trademark, patent, or other intellectual property or proprietary rights notices from the Application, including any copy thereof;</li>
                <li>e). rent, lease, lend, sell, sublicense, assign, distribute, publish, transfer, or otherwise make available the Application, or any features or functionality of the Application, to any third party for any reason, including by making the Application available on a network where it is capable of being accessed by more than one device at any time; or</li>
                <li>f). remove, disable, circumvent, or otherwise create or implement any workaround to any copy protection, rights management, or security features in or protecting the Application.</li>
            </ul>
            <p>3.  <u>Reservation of Rights</u>. You acknowledge and agree that the Application is provided under license, and not sold, to you. You do not acquire any ownership interest in the Application under this Agreement, or any other rights thereto other than to use the Application in accordance with the license granted, and subject to all terms conditions, and restrictions, under this Agreement. Company and its licensors and service providers reserve and retain their entire right, title, and interest in and to the Application, including all copyrights, trademarks, and other intellectual property rights therein or relating thereto, except as expressly granted to you in this Agreement.</p>
            <p>4.  <u>Collection and Use of Your Information</u>. </p>
            <ul style="line-height: 28px;">
              <li>(a)	You acknowledge that when you use the Application, Company may use automatic means (including, for example, cookies and web beacons) to collect information about your use of the Application. You also may be required to provide certain information about yourself as a condition to using the Application or certain of its features or functionality, and the Application may provide you with opportunities to share information about yourself with others. All information we collect through or in connection with this Application is subject to our Privacy Statement & Business Associate Agreement <a href="https://linkboxnow.com">linkboxnow.com</a>. By using and providing information to or through this Application, you consent to all actions taken by us with respect to your information in compliance with the Privacy Statement & Business Associate Agreement.  Without limiting the generality of the foregoing, Company may monitor your use of the Application and collect and compile data and information about your use of the Application in an aggregate and anonymized manner, including to compile statistical and performance information related to the provision and operation of the Application (“Aggregated Statistics”). As between Company and you, all right, title, and interest in Aggregated Statistics, and all intellectual property rights therein, belong to and are retained solely by Company. You acknowledge that Company may compile Aggregated Statistics based on PHI input into the Application. You agree that Company may (i) make Aggregated Statistics publicly available in compliance with applicable law, and (ii) use Aggregated Statistics to the extent and in the manner permitted under applicable law; provided that such Aggregated Statistics do not include PHI.</li>
            </ul>
            <p>5. <u>Content and Services</u>. The Application may provide you with access to Company’s website located at www.linkboxnow.com and www.linkboxsolutions.com (the “<b>Website</b>”) and products and services accessible thereon, and certain features, functionality, and content accessible on or through the Application may be hosted on the Website (collectively, “<b>Content and Services</b>”). Your access to and use of such Content and Services are governed by Website’s Terms of Use and Privacy Statement & Business Associate Agreement located at <a href="<?php echo e(URL::to('terms-of-use')); ?>">Terms of Use</a> and <a href="<?php echo e(URL::to('privacy-statement')); ?>">Privacy Statement</a>, which are incorporated herein by this reference. Your access to and use of such Content and Services may require you to acknowledge your acceptance of such Terms of Use and Privacy Statement and/or to register with the Website, and your failure to do so may restrict you from accessing or using certain of the Application’s features and functionality. Any violation of such Terms of Use will also be deemed a violation of this Agreement.</p>
            <p>6. <u> Privacy and Security</u>.  Company acknowledges and agrees that you may create, access, maintain, or transmit Protected Health Information (“PHI”) using the Application.  As such, Company  will employ security measures in accordance with HIPAA and will comply with the terms of the Privacy Statement & Business Associate Agreement.</p>
            <ul style="line-height: 28px;">
              <li>a) You retain sole responsibility for: (i) all PHI, including verification of its content and accuracy and  any required consent for its collection and use; (ii) all information, instructions, and materials provided by you in connection with using the Application; (iii) your information technology infrastructure, including computers, software, databases, electronic systems (including database management systems), and networks; (iv) the security and use of your access credentials; and (v) all access to and use of the Application, including all results obtained from, and all conclusions, decisions, and actions based on, such access or use.</li>
              <li>b) You will employ all physical, administrative, and technical controls, screening, and security procedures and other safeguards necessary to: (i) securely administer the distribution and use of all access credentials and protect against any unauthorized access to or use of the Application; and (b) control the content and use of PHI, including the uploading or other provision of PHI for processing by the Application.</li>
              <li>c) Use of the Application does not replace your need  to maintain regular data backups or redundant data archives. All PHI is deleted from the Application in accordance with Company’s standard document retention and deletion policies and procedures. COMPANY HAS NO OBLIGATION OR LIABILITY FOR ANY LOSS, ALTERATION, DESTRUCTION, DAMAGE, CORRUPTION, OR RECOVERY OF PHI.</li>
              <li>d) U.S. Compliance.  This Agreement is intended for healthcare practices operating strictly within the U.S with no operations in the territories that have adopted the regulations of other jurisdictions, for example the European Union’s General Data Protection Regulation (GDPR). You agree you will make no attempts to market toward or treat residents in foreign jurisdictions using the Application</li>
            </ul>
            <p>7.  <u>Updates</u>. Company may from time to time in its sole discretion develop and provide Application updates, which may include upgrades, bug fixes, patches, other error corrections, and/or new features (collectively, including related documentation, “<b>Updates</b>”). Updates may also modify or delete in their entirety certain features and functionality. You agree that Company has no obligation to provide any Updates or to continue to provide or enable any particular features or functionality. </p>
            <p>8.  <u>Third-Party Materials</u>. The Application may display, include, or make available third-party content (including data, information, applications, and other products, services, and/or materials) or provide links to third-party websites or services, including through third-party advertising (”<b>Third-Party Materials</b>”). You acknowledge and agree that Company is not responsible for Third-Party Materials, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality, or any other aspect thereof. Company does not assume and will not have any liability or responsibility to you or any other person or entity for any Third-Party Materials. Third-Party Materials and links thereto are provided solely as a convenience to you, and you access and use them entirely at your own risk and subject to such third parties’ terms and conditions.</p>
            <p>9.  <u>Fees</u>.  As consideration for the License Grant described in this Agreement, you agree to pay fees as described in the <a href="<?php echo e(URL::to(@$redirect)); ?>">Subscription</a>.</p>
            <p>10. <u>Term and Termination</u>.</p>
            <ul style="line-height: 28px;">
              <li>(a)  The term of this Agreement commences when you acknowledge your acceptance and will continue in effect for a period of [one year] unless terminated by Company as set forth in this Section 10.</li>
              <li>(b) Company may terminate this Agreement at any time without notice if it ceases to support the Application, which Company may do in its sole discretion. In addition, this Agreement will terminate immediately and automatically without any notice if you violate any of the terms and conditions of this Agreement.</li>
              <li>(c)  Upon termination:
                <ul style="line-height: 28px;">
                  <li>(i)  all rights granted to you under this Agreement will also terminate; and</li>
                  <li>(ii)  you must cease all use of the Application</li>    
                </ul>
              </li>
              <li>(d)  Termination will not limit any of Company’s rights or remedies at law or in equity.</li>
            </ul>
            <p>11. <u>Disclaimer of Warranties</u>. THE APPLICATION IS PROVIDED TO YOU “AS IS” AND WITH ALL FAULTS AND DEFECTS WITHOUT WARRANTY OF ANY KIND. TO THE MAXIMUM EXTENT PERMITTED UNDER APPLICABLE LAW, COMPANY, ON ITS OWN BEHALF AND ON BEHALF OF ITS AFFILIATES AND ITS AND THEIR RESPECTIVE LICENSORS AND SERVICE PROVIDERS, EXPRESSLY DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO THE APPLICATION, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT, AND WARRANTIES THAT MAY ARISE OUT OF COURSE OF DEALING, COURSE OF PERFORMANCE, USAGE, OR TRADE PRACTICE. WITHOUT LIMITATION TO THE FOREGOING, COMPANY PROVIDES NO WARRANTY OR UNDERTAKING, AND MAKES NO REPRESENTATION OF ANY KIND THAT THE APPLICATION WILL MEET YOUR REQUIREMENTS, ACHIEVE ANY INTENDED RESULTS, BE COMPATIBLE, OR WORK WITH ANY OTHER SOFTWARE, APPLICATIONS, SYSTEMS, OR SERVICES, OPERATE WITHOUT INTERRUPTION, MEET ANY PERFORMANCE OR RELIABILITY STANDARDS OR BE ERROR-FREE, OR THAT ANY ERRORS OR DEFECTS CAN OR WILL BE CORRECTED.</p>
            <p>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF OR LIMITATIONS ON IMPLIED WARRANTIES OR THE LIMITATIONS ON THE APPLICABLE STATUTORY RIGHTS OF A CONSUMER, SO SOME OR ALL OF THE ABOVE EXCLUSIONS AND LIMITATIONS MAY NOT APPLY TO YOU.</p>
            <p>12.  <u>Limitation of Liability</u>. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL COMPANY OR ITS AFFILIATES, OR ANY OF ITS OR THEIR RESPECTIVE LICENSORS OR SERVICE PROVIDERS, HAVE ANY LIABILITY ARISING FROM OR RELATED TO YOUR USE OF OR INABILITY TO USE THE APPLICATION OR THE CONTENT AND SERVICES FOR:</p>
            <ul style="line-height: 28px;">
              <li>(a)  PERSONAL INJURY, PROPERTY DAMAGE, LOST PROFITS, COST OF SUBSTITUTE GOODS OR SERVICES, LOSS OF DATA, LOSS OF GOODWILL, BUSINESS INTERRUPTION, COMPUTER FAILURE OR MALFUNCTION, OR ANY OTHER CONSEQUENTIAL, INCIDENTAL, INDIRECT, EXEMPLARY, SPECIAL, OR PUNITIVE DAMAGES.</li>
              <li>(b)  DIRECT DAMAGES IN AMOUNTS THAT IN THE AGGREGATE EXCEED THE AMOUNT ACTUALLY PAID BY YOU FOR THE APPLICATION.</li>
            </ul>
            <p>THE FOREGOING LIMITATIONS WILL APPLY WHETHER SUCH DAMAGES ARISE OUT OF BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE), OR OTHERWISE AND REGARDLESS OF WHETHER SUCH DAMAGES WERE FORESEEABLE OR COMPANY WAS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW CERTAIN LIMITATIONS OF LIABILITY SO SOME OR ALL OF THE ABOVE LIMITATIONS OF LIABILITY MAY NOT APPLY TO YOU.</p>
            <p>13.   <u>Indemnification</u>. You agree to indemnify, defend, and hold harmless Company and its officers, directors, employees, agents, affiliates, successors, and assigns from and against any and all losses, damages, liabilities, deficiencies, claims, actions, judgments, settlements, interest, awards, penalties, fines, costs, or expenses of whatever kind, including attorneys’ fees, arising from or relating to your use or misuse of the Application or your breach of this Agreement, including but not limited to the content you submit or make available through this Application.</p>
            <p>14.  <u>Severability</u>. If any provision of this Agreement is illegal or unenforceable under applicable law, the remainder of the provision will be amended to achieve as closely as possible the effect of the original term and all other provisions of this Agreement will continue in full force and effect.</p>
            <p>15.   <u>Governing Law</u>. This Agreement is governed by and construed in accordance with the internal laws of the State of Florida without giving effect to any choice or conflict of law provision or rule. Any legal suit, action, or proceeding arising out of or related to this Agreement or the Application shall be instituted exclusively in the federal courts of the United States or the courts of the State of Florida. You waive any and all objections to the exercise of jurisdiction over you by such courts and to venue in such courts.</p>
            <p>16. <u>Entire Agreement</u>. This Agreement, the Terms of Use, and our Privacy Statement & Business Associate Agreement constitute the entire agreement between you and Company with respect to the Application and supersede all prior or contemporaneous understandings and agreements, whether written or oral, with respect to the Application.</p>
            <p>17.  <u>Waiver</u>.  No failure to exercise, and no delay in exercising, on the part of either party, any right or any power hereunder shall operate as a waiver thereof, nor will any single or partial exercise of any right or power hereunder preclude further exercise of that or any other right hereunder. In the event of a conflict between this Agreement and any applicable purchase or other terms, the terms of this Agreement will govern.</p>
        <div class="clearfix"></div>
        <!--Content Area End-->
        <input type="checkbox" value="1" id="termsAgreement"> I agree to the  <a href="<?php echo e(URL::to('terms-of-use')); ?>" target="_blank">Terms of Use</a> and <a href="<?php echo e(URL::to('privacy-statement')); ?>" target="_blank">Privacy Statement</a>.
      </div>
      <div class="modal-footer">
        <!-- <button type="button" class="btn btn-default" data-dismiss="modal" id="agreementCancel">Decline</button> -->
        <button type="button" class="btn btn-primary" id="acceptAgreement">I Agree</button>
      </div>
    </div>

  </div>
</div>
<!-- Modal of User Accepts the Terms & Conditions content End-->