@extends('layouts.default')

@section('content')
<!--Content Area-->
<div class="about-content-area" id="about-us">

    <div class="container">

        <div class="about-text-main">

            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 about-text">
                <h1>Privacy Statement</h1> 
                <h3>Introduction</h3>
                <p>LinkBox Solutions and its affiliates and properties (“us”, “we”, “our”, or “Company”) respect the privacy of our users.  This Privacy Statement will tell you how and what information we may receive about you, and how we may use your information when providing you our tools, products and services. Please read this Privacy Statement carefully.</p>
                <p>This Privacy Statement applies to any website that we own and operate, including www.linkboxnow.com and any mobile optimized versions of the site (the “Site”). Except where expressly noted, this Privacy Statement also applies to any mobile device applications or web-based applications owned or operated by us.</p>

                <h3>Personal Information Collected</h3>
                <p>In connection with the tools, products and services provided through our Site, some of the information you provide may be personal information (“Personal Information”). Depending on the tools, products or service, some of the Personal Information you provide may be personal health information (“Personal Health Information”). Also, some information we receive through such tools, products and services may be non-Personal Information. You are responsible for ensuring the accuracy of the Personal Information and Personal Health Information you provide to us. Inaccurate information may affect the information you receive when using such tools, products and services. For Personal Health Information collected through our Site, we agree to comply with the Business Associate Agreement contained herein.</p>
                <h3>We may receive Personal Information that you provide to us as follows:</h3>
                <p><u>Registration Information:</u> You may share Personal Information with us through newsletters, trade shows, conferences, tools or other services provided by us (and as part of the foregoing).  You may share Personal Information when you register on our Site or when you use either or web-based or downloaded application (the “Services”). The information you share with us may be changed by you by notifying us or by following the instructions provided to you by us at registration.</p>
                <p><u>Use of our Services:</u>  When you use or interact with our Services, you input Personal Information (which may include Personal Health Information).</p>
                <p><u>Community Areas, Chats, Postings, Bulletin Boards, Blogs and other User Forums:</u>  We may provide an opportunity for users to communicate in community areas, postings, wikis, bulletin boards, chat rooms, blogs and other public and interactive forums on or through our Site (“User Forums”). Any User Forums available are open to the public and should not be considered private.</p>
                <p><u>Interactive Tools:</u>We may offer you interactive content, tools and services. In connection with such items, we may receive information, including Personal Information, which you voluntarily share with us. Some of the tools (like certain quizzes) do not retain your Personal Information, while others (like tools offered through Apps) may store your Personal Information.</p>
                <p><u>Use of Personal Information</u></p>
                <p>We may disclose and use Personal Information to comply with valid legal requirements such as a law, regulation, search warrant, subpoena or court order; or in special cases, such as in response to a physical threat, to prevent or stop actual or potential harm to you, the Company, its users, their property, or defend or assert legal rights. </p>
                <p>In addition, we may use Personal Information to provide you the Services requested or agreed by you; communicate with you on the tools, products and services requested or agreed by you (or their terms) and respond to questions you have about the tools, products and services we provide you; help us design and improve our Site and Services, tools, business, products and services to better suit your needs and interests; enable you to participate in features and offers; enforce our policies and procedures, or enforce any other agreement we have with you; help with billing and collection (if applicable) on services and products requested by you; comply with your instructions, authorization or request; and for any other purpose disclosed to you at the time we receive your information or pursuant to your consent.</p>
                <p>We may use Personal Information to develop and provide you advertising, marketing and promotions, or information on services, offerings or products that may be of interest to you. You may opt-out from having Personal Information used for this type of communication by contacting us at any time. Please allow for up to 30 days after your election for the opt-out to take effect.</p>
                <p>Personal Information may be provided in connection with the foregoing uses to our affiliates, representatives and personnel, contractors who perform functions on our behalf, and certain strategic partners and third parties.</p>
                <h3>Non-Personal Information Collected</h3>
                <p>We may collect non-Personal Information as follows:</p>
                <p><u>Cookies and Web Beacons</u></p>
                <p>We may receive information through the use of cookies, web beacons, and similar technology. Cookies are pieces of data that a website transfers to a user’s hard drive for record-keeping purposes. Web beacons are transparent pixel images that are used in collecting information about website usage, e-mail response and tracking.</p>
                <p>This Site may use cookies and Web beacons to provide enhanced functionality on the site (e.g., event registration) and aggregate traffic data (e.g., what pages are the most popular). These cookies may be delivered in a first-party or third-party context. We also may use cookies and web beacons in association with e-mails delivered by us. Our Site may also capture limited information (user-agent, HTTP referrer, last URL requested by the user, client-side and server-side clickstream) about visits to our Site; we may use this information to analyze general traffic patterns and to perform routine system maintenance. You have many choices with regards to the management of cookies on your computer. All major browsers allow you to block or delete cookies from your system. To learn more about your ability to manage cookies and web beacons, please consult the privacy features in your browser.</p>
                <p>A designated service provider, or third-party advertisers or their advertising servers may also place or recognize unique cookies on your device or use similar electronic tools in order to display advertisements that you see on our Site. Information about your visits to, and activity on, our Site, an IP address, as well as the number of times you have viewed an advertisement, are used to display on your device screen customized advertisements that may be of particular interest to you. We do not have access to, or control the information collected by, these cookies or similar electronic tools used by these third-party advertisers or their advertising servers. The use and collection of your information by these third-party advertisers and advertising servers is not covered by this Privacy Statement. For information about advertising networks and how to “opt out” of cookies placed by the third parties, please contact the third party companies.</p>
                <p>Our designated service provider may assist us with advertisement display functions for our Site.  For more information about such provider’s handling of non-Personal Information and use practices, including the use of cookies, as well as its instructions on how to “opt out” of having your Site usage information collected or used by such provider, please contact us. When you opt out via this method, you officially opt out of such provider’s advertisement display programs for your device’s particular web browser. You need to opt out for each browser, on each device you use to surf the web. Similarly, if you connect to the web from multiple devices (e.g., work and home), you need to explicitly opt out from each browser on each device.</p>
                <p>Most browsers are set to accept cookies by default. If you prefer, you can usually set your browser to disable cookies, or to alert you when cookies are being sent. The help function on most browsers contains instructions on how to set your browser to notify you before accepting cookies or to disable cookies entirely. However, it is possible that some parts of this Web site, such as the polls, surveys, contests, product sales, and game areas, will not function properly if you disable cookies.</p>
                <p>Our Site may also use web analytics services provided by service providers (e.g., Google).  Such providers may use cookies to help the Site analyze how users use the Site. The information generated by the cookie about your use of our Site (including your IP address) may be transmitted to and stored by such providers.  Such providers may use this information for the purpose of evaluating your use of the Site, compiling reports on Site activity for Site operators and providing other services relating to Site activity and internet usage. Such providers may also transfer this information to third parties where required to do so by law, or where such third parties process the information on such provider’s behalf.  You may refuse the use of cookies by selecting the appropriate settings on your browser as described above, however please note that if you do this you may not be able to use the full functionality of our Site.</p>
                
                <p><u>Third Party Advertisers</u></p>
                <p>As mentioned above, sponsors or advertisers on the Site may use their own cookies, web beacons or other online tracking technologies in the advertisements served on our Site and in emails, special promotions, newsletters or communication we send you. Some advertisers use companies other than us to serve their advertisement and to monitor users’ responses to advertisement, and these companies (“Ad Servers”) may also receive non-Personal Information through the use of cookies or web beacons. In certain situations, information collection may be facilitated by momentarily directing your browser to the website of an Ad Server or other third party acting on behalf of the sponsor or advertiser before re-directing your browser to its selected destination. This re-direction process may not be apparent to you.</p>
                <p>We do not control third party’s use of cookies or web beacons, or how they manage the non-Personal Information they receive. You should not provide Personal Information to such sponsors, advertisers and Ad Servers without your consent. Certain Ad Servers allow you to prevent such third party’s from collecting data through the use of cookies. In order to do so, you must opt out of such data collection with each individual site. </p>
                <p>Some of the information gathered from the use of cookies, web beacons and similar technology is described below.</p>
                
                <p><u>Information from Video</u></p>
                <p>We may receive non-Personal Information about your interactions with video content (if any) on this Web site, such as the type of content viewed and information about your interactions with email messages (e.g., links clicked on and whether the messages were opened or forwarded).</p>
                
                <p><u>Information on Web pages and Links</u></p>
                <p>We may receive non-Personal Information on web pages and advertisements you view from the website and links within the website.</p>
                
                <p><u>URL, Browser Type, Operating Systems and IP Address</u></p>
                <p>Like many other websites, we may receive non-Personal Information about our users’ utilization, activity and navigation of our website, websites of selected sponsors and advertisers, your browser type, IP protocol and operating system.</p>
                <p><u>Third Party Sources</u></p>
                <p>We may receive non-Personal Information from other sources, such as through vendors and service providers with authorized rights to such information, and from publicly available sources.</p>
                <p><u>Use of Non-Personal Information</u></p>
                <p>The paragraphs described above outline some of our uses of non-Personal Information.  We may also use non-Personal Information to help us monitor how many people are using our Site and selected sponsors’ and advertisers’ sites, to provide enhanced functionality on the Site (e.g., user ID and password prompts, navigation aids, and session timers), to help us generate and deliver advertising, marketing and content on web pages or any of our other properties, to monitor certain other Site activity (e.g., user-agent, last URL requested by the user, client-side and server-side clickstream, age restrictions), to monitor how many people open our emails, and for functions related to the foregoing.</p>
                <p>We may also use and share non-Personal Information in the same manner as our use of Personal Information described below and in connection with our business (e.g., our third party contractors, agents and representatives may help us utilize cookies and web beacons, and store/handle non-Personal Information).</p>
                <h3>Children</h3>
                <p>We are committed to protecting the privacy of children. Neither the Company nor any of our services are designed or intended to attract children under the age of 13. We do not collect Personal Information from any person we actually know is under the age of 13. If we obtain actual knowledge that we have received such information, we will take steps to delete it.</p>
                <h3>Information Security</h3>
                <p>We have in place reasonable commercial standards of technology and operational security to protect all personal information provided by users via the Site from unauthorized access, disclosure, alteration or destruction.</p>
                <h3>Accessing and Updating Your Personal Information</h3>
                <p>To access, review, rectify, or delete Personal Information collected about you, please contact us. All requests must include the following information: first name, last name, e-mail address, and known location of Personal Information controlled by us. While we try our best to accommodate your request, we reserve the right to impose certain restrictions and requirements on such access requests, if allowed or required by applicable laws, and not all information is removable.</p>
                <h3>Links To Third-Party Web Sites</h3>
                <p>This Privacy Statement only addresses the use and disclosure by our Company of your information. We may provide links to third-party websites.  We do not control third-party sites and are not responsible for any information you may provide while on such sites.  We are not liable for their use or misuse of your information. You should read the privacy policies on those websites before providing any of your information on such sites.</p>
                <h3>Legal Notice and Disclaimer</h3>
                <p>References herein to any product, process or service do not constitute or imply endorsement or recommendation by us, nor does it constitute a formal offer, binding obligation or agreement to provide such product, process or service under any circumstances. While we make every effort to present accurate and reliable information on our Site and other tools, products and services, we do not approve or certify such information nor does it guarantee the accuracy, completeness, efficacy, timeliness or correctness of such information. Use of such information is voluntary and reliance on it should only be undertaken after an independent review of its applicability, accuracy, completeness, efficacy and timeliness with regard to a user’s specific needs and uses. The Company (including its employees and agents) is not responsible for, and expressly disclaims all liability for, damages of any kind arising out of use, reference to or reliance on the information available through its tools, products, and services to which this Privacy Statement is linked or referenced. No approvals, recommendations, endorsements, guarantees or warranties, including, but not limited to, any express or implied warranties of merchantability or fitness for any particular use or purpose of tools, products or services provided by us.</p>
                <h3>Conditions on Use</h3>
                <p>By using our tools, products, and services which this Privacy Statement is linked or referenced, you agree to the terms and conditions contained in this Privacy Statement or the Site’s Terms of Use, and any other agreement that we might have with you concerning the use herein. If you do not agree to any of these terms and conditions, you should not use such tools, products or services. If you have entered into another agreement with us about the confidentiality of your information, that agreement will control if there is a conflict. </p>
                <h3>Questions Regarding This Privacy Statement</h3>
                <p>If you have questions regarding this Privacy Statement, please contact us at info@linkboxnow.com or by mail at 13506 Summerport Village Pkwy #405 Windermere, Florida 34786.</p>
                <h3>Modifications To This Privacy Statement</h3>
                <p>We may modify or amend this Privacy Statement from time to time at our discretion. When we make changes to this Privacy Statement, we will amend the revision date at the top of this page and such modified or amended Privacy Statement shall be effective as to you and your information as of that revision date. We encourage you to periodically review this Privacy Statement to view any updates.</p>
                <h3>US Compliance</h3>
                <p>Our Site is  intended for healthcare practices operating strictly within the U.S with no operations in the territories that have adopted the regulations of other jurisdictions, for example the European Union’s General Data Protection Regulation (GDPR). You agree you will make no attempts to market toward or treat residents in foreign jurisdictions using the Site.</p>
                <h3>Business Associate Agreement</h3>
                <p>To the extent you create, access, maintain, or transmit Protected Health Information on our Site, the following Business Associate Agreement applies:</p>
                <p>This Business Associate Agreement (this “BAA”) by and between you (“Covered Entity”) and Company ( “Business Associate”) is entered into as a part of the Privacy Statement and is incorporated by reference therein.</p>
                <p>For valuable consideration the receipt and sufficiency of which is acknowledged by both parties, the parties agree as follows:</p>
                <p>
                    <ol style="list-style-type: decimal; padding-left:2em; line-height: 1.5;">
                        <li>
                            <b><u>Definitions.</u></b>
                            <ol style="list-style-type: lower-alpha; padding-left:2em;">
                                <li><i>&quot; Protected Health Information &quot;</i> (PHI) has the same meaning as the term &quot;protected health information&quot; in 45 CFR § 164.501, limited to the information created or received by Business Associate from or on behalf of Covered Entity.</li>
                                <li><i>&quot;HIPAA Rules&quot;</i> means the Privacy, Security, Breach Notification, and Enforcement Rules at 45 CFR § 160 and 45 CFR § 164. </li>
                            </ol>
                        </li>   
                        <li>
                            <b><u>Obligations and Activities of Business Associate</u></b>
                            <ol style="list-style-type: lower-alpha; padding-left:2em;">
                                <li><u>Not to Use or Disclose PHI Unless Permitted or Required.</u> Business Associate agrees to not use or disclose PHI other than as permitted or required by the Agreement, this BAA,  as required by law, or as otherwise authorized by Covered Entity.</li>
                                <li><u>Use Safeguards.<</u> Business Associate agrees to comply with Subpart C of 45 CFR § 164 and to use appropriate safeguards to prevent use or disclosure of PHI other than as provided for by this BAA.  Business Associate will implement administrative, physical, and technical safeguards that reasonably and appropriately protect the confidentiality, integrity, and availability of any electronic PHI that Business Associate creates, receives, maintains, or transmits on behalf of Covered Entity.</li>
                                <li><u>Report Unpermitted Disclosures of PHI.</u> Business Associate agrees to report to Covered Entity any use or disclosure of PHI not provided for by this BAA of which it becomes aware, , including without limitation breaches of unsecured PHI as required by 45 CFR § 164.410.</li>
                                <li><u>Compliance of Subcontractors and Agents.</u> Business Associate agrees to ensure that any subcontractor or agent,  to whom it provides PHI created, received, maintained or transmitted by .  Business Associate on behalf of Covered Entity, agrees to the same restrictions, conditions, and requirements that apply through this BAA to Subcontractor with respect to such PHI.</li>
                                <li><u>Provide Access.</u> Business Associate agrees to provide access, during normal business hours, to PHI  in a Designated Record Set to Covered Entity in order to meet the requirements under 45 CFR § 164.524, provided Covered Entity delivers written notice to Business Associate at least 30 days in advance requesting such access.  This provision does not apply if Business Associate has no PHI in a Designated Record Set of Covered Entity or if the PHI held by Business Associate merely duplicates information held by Covered Entity.</li>
                                <li><u>Incorporate Amendments.</u> Business Associate agrees to make any amendment(s) to PHI in a Designated Record Set of Covered Entity that Covered Entity directs to pursuant to 45 CFR § 164.526.  This provision does not apply if Business Associate has no PHI in a Designated Record Set of Covered Entity.</li>
                                <li><u>Accounting for Disclosures.</u> Business Associate agrees to maintain sufficient documentation of such disclosures of PHI by Business Associate as would be required for Covered Entity to respond to a request by an Individual for an accounting of disclosures of PHI in accordance with 45 CFR § 164.528.  On request of Covered Entity, Business Associate agrees to provide to Covered Entity documentation made in accordance with this Section to permit Covered Entity to respond to a request by an Individual for an accounting of disclosures of PHI in accordance with 45 CFR § 164.528.  Business Associate shall have a reasonable period of time within which to comply with requests for such a request from Covered Entity and in no case shall Business Associate be required to provide such documentation in less than five business days after Business Associate’s receipt of such request.</li>
                                <li><u>Requests from Individuals.</u> Except as this BAA or any other agreement between Covered Entity and Business Associate may otherwise provide, in the event Business Associate receives an access, amendment, accounting of disclosure, or other similar request directly from an Individual, Business Associate will direct the Individual to Covered Entity.</li>
                                <li><u>Obligations of Covered Entity.</u> To the extent Business Associate is to carry out Covered Entity’s obligations under Subpart E of 45 CFR § 164, Business Associate will comply with the requirements of Subpart E of 45 CFR § 164 that apply to Covered Entity.</li>
                                <li><u>Books and Records.</u> Unless otherwise protected or prohibited from disclosure or discovery by law, Business Associate agrees to make internal practices, books, and records relating to the use and disclosure of PHI available to the Secretary for purposes of the Secretary determining Covered Entity’s compliance with the HIPAA Rules.  Business Associate shall have a reasonable period of time within which to comply with requests for such access and in no case shall access be required in less than five business days after Business Associate’s receipt of such request, unless otherwise designated by the Secretary.</li>
                                <li><u>Prohibition Against Sale or Marketing of PHI.</u> Business Associate will not directly or indirectly receive remuneration in exchange for any PHI of an individual, or use or disclose PHI for any purpose related directly or indirectly to any marketing or marketing communication.</li>
                            </ol>
                        </li>
                        <li>
                            <b><u>Permitted Uses and Disclosures by Business Associate.</u>3.Business Associate may not use or disclose PHI in a manner that would violate the HIPAA Rules.</b>
                            <ol style="list-style-type: lower-alpha; padding-left:2em;">
                                <li><u>Services and Activities on Behalf of Covered Entity.</u> Except as otherwise limited in this BAA, Business Associate may use or disclose PHI to perform functions, activities, or services for, or on behalf of, Covered Entity as specified in the Agreement, provided that such use or disclosure would not violate the HIPAA Rules if done by Covered Entity.</li>
                                <li><u>Management and Administration.</u> Except as otherwise limited in this BAA, Business Associate may use PHI for the proper management and administration of the Business Associate or to carry out the legal responsibilities of the Business Associate, provided that disclosures are either: (i) Required by Law; or (ii) Business Associate obtains reasonable assurances from the person to whom the information is disclosed that it will remain confidential and used or further disclosed only as Required by Law or for the purpose for which it was disclosed to the person, and the person notifies the Business Associate of any instances of which it is aware in which the confidentiality of the information has been breached.</li>
                                <li><u>De-Identification / Data Aggregation.</u> Business Associate may de-identify PHI and/or e-PHI received or created pursuant to the Agreement, provided that the de-identification process conforms to the requirements of 45 C.F.R. § 164.514(b), and may perform Data Aggregation, including services to Covered Entity as permitted by 45 CFR § 164.504(e)(2)(i)(B).</li>
                            </ol>
                        </li>
                        <li>
                            <b><u>Term and Termination</u></b>
                            <ol style="list-style-type: lower-alpha; padding-left:2em;">
                                <li><u>Term.</u> The Term of this BAA shall be effective as of the Effective Date, and shall terminate when all of the PHI provided by Covered Entity to Business Associate, or created or received by Business Associate on behalf of Covered Entity, is destroyed or returned to Covered Entity, or, if it is infeasible to return or destroy PHI, protections are extended to such information, in accordance with the termination provisions in this Section.</li>
                                <li><u>Termination for Cause.</u> Upon Covered Entity’s reasonable determination that Business Associate has breached or violated a material term of this BAA or if Covered Entity knows or has reason to know of a pattern of activity or practice of Business Associate that constitutes a material breach, Covered Entity shall give Business Associate written notice of such breach and provide reasonable opportunity for Business Associate to cure such breach or end the violation.  Covered Entity may terminate this BAA, and Business Associate agrees to such termination, if Business Associate has breached a material term of this BAA and does not cure the breach or cure is not possible.</li>
                                <li><u>Effect of Termination.</u> Upon termination of the business relationship between Business Associate and Covered Entity and receipt of written demand from Covered Entity, Business Associate agrees to, if feasible, return or destroy all PHI received from, or created or received by Business Associate on behalf of Covered Entity.  In the event that Business Associate determines that returning or destroying such PHI is not feasible, the protections of this BAA will remain in force and Business Associate shall make no further uses and disclosures of PHI except for the proper management and administration of its business or to carry out its responsibilities or as required by law.</li>
                            </ol>
                        </li>   
                        <li>
                            <b><u>Miscellaneous</u></b>
                            <ol style="list-style-type: lower-alpha; padding-left:2em;">
                                <li><u>Amendment</u> The Parties agree to take such action as is necessary to amend this BAA from time to time as is necessary for Covered Entity to comply with the requirements of the HIPAA Rules.  Specifically, Business Associate hereby acknowledges and agrees that to the extent it functions as a business associate of Covered Entity, Business Associate will comply with the HIPAA Rules and with the obligations of a business associate as proscribed by the HIPAA Rules commencing on the applicable effective date of each such provision.  Business Associate and Covered Entity further agree that the provisions of HIPAA Rules that apply to business associates and that are required to be incorporated by reference in a business associate agreement are incorporated into this BAA as if set forth herein.</li>
                                <li><u>Notices.</u> All notices, consents, waivers and other communications under this BAA must be in writing and will be deemed to have been duly given when sent by electronic mail (with written confirmation of receipt), provided that a copy is mailed by registered mail, return receipt requested or a nationally recognized overnight delivery service (receipt requested), to the appropriate addresses as a party may designate by notice to the other party.</li>
                                <li><u>Survival.</u> The respective rights and obligations of Business Associate under Section 4(c) of this BAA shall survive the termination of this BAA.</li>
                                <li><u>Interpretation.</u> Any ambiguity in this BAA shall be resolved to permit compliance with the HIPAA Rules.</li>
                                <li><u>Binding Effect.</u> Entry into the Agreement constitutes entry into this BAA and no separate signatures or execution is required</li>
                            </ol>
                        </li>  
                    </ol>
                </p>
            </div>

        <div class="clearfix"></div>
        </div>

    </div>
</div>
<!--Content Area End-->
@endsection

@section('contact')
@include('includes.contact')
@endsection